services:
  flask:
    build: ./app
    container_name: flask
    restart: always
    expose:
      - "5000"
    env_file:
      - .env

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - flask
