services:
  flask:
    build: ./app
    container_name: flask
    restart: always
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      #- ./certbot/webroot:/var/www/certbot
      #- ./certbot/letsencrypt:/etc/letsencrypt
    depends_on:
      - flask

  #certbot:
  #image: certbot/certbot:latest
  #container_name: certbot
  #volumes:
  #- ./certbot/webroot:/var/www/certbot
  #- ./certbot/letsencrypt:/etc/letsencrypt
