FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN python preload_model.py

CMD [ "gunicorn", "--bind", "0.0.0.0:5000", "app:app" ]